## 2.3. &nbsp; Install Matlab on your local computer

Currently, it is necessary to use Matlab to run the data cleaning scripts. 

* First, check which Matlab version is currently recommended for the pipeline code, in section 8.2. While the data pipeline will most likely work with other recent versions of Matlab, we make no guarantees of cross compatibility.

* Visit <a href="https://www.mathworks.com/help/install/ug/install-products-with-internet-connection.html" target="_blank" rel="noopener noreferrer">this website</a> for details on how to install Matlab, or contact your systems administrator for help. 

* Make sure you install Matlab with the following toolboxes:
    1. Curve fitting
    2. Global Optimization
    3. Optimization
    4. Signal Processing
    5. Statistics and Machine Learning.

    Additional toolboxes may be available depending on your institutional/personal licence. However, having every available toolbox installed is likely a waste of your disk space, and is not required for the data pipeline.

* If you already have the correct version of Matlab on your local computer, you can install the necessary toolboxes using the “Add-Ons” button in the “Home” tab within Matlab.

* When you have Matlab along with the relevant toolboxes installed, you are ready to configure it to use with the Biomet.net library.

**NOTE**: you can have more than one version of Matlab on your computer in case you prefer to use another version of Matlab for other projects.
