## 5.5. &nbsp; Quick Start: Third Stage Cleaning and Converting to Ameriflux Output

<link rel="stylesheet" href="css/style.css"> 

This section is intended to complement the instructions for third stage cleaning provided in the tutorial in section 4.5. Here we provide further details of outlier removal algorithms and u-star filtering. 

On this page:

- <a href="#div_id_GeneralThirdStage">General outline for creating your third stage YML configuration file</a>
- <a href="#div_id_RunThirdStage">Running third stage cleaning in Matlab</a>
- <a href="#div_id_FiltersThirdStage">Third stage filters and variable names</a>
- <a href="#div_id_RunAmerifluxStage">Output to Ameriflux CSV file</a>
- <a href="#div_id_Tips">Tips</a>

<br>

<div id="div_id_GeneralThirdStage">

<hr>

### General outline for creating your third stage YML configuration file

As with the first and second stage cleaning, if you are doing this for the first time, we recommend that you obtain the simplified template files from the quick-start instructions in section 4 and follow the tutorial. The third stage cleaning generally requires the least amount of work of the three stages, and here are the steps:

* Open your site-specific `SITEID1_config.yml` for editing.
* Fill in the details for your site in the "Metadata" section at the top of the file. The `northOffset` can be found in your site GHG biomet file and this information is used for filtering data by wind direction, to comply with eddy-covariance measurement standards.
* Make sure that you are processing the correct fluxes as measured at your site, under Processing -> ThirdStage -> Fluxes, and input `NULL` for any fluxes not measured at your site.
* Check the met variable names used for gap-filling are named the same as those output by your second stage cleaning, under Met_Gap_Filling -> Linear_Interpolation -> Fill_Vars.

The main configuration file (`global_config.yml`) for running third stage cleaning is located in the `Biomet.net` library and generally speaking this should not be edited. The custom `SITEID1_config.yml` file can be used to add parameters/inputs; these site-specific settings will overwrite those in the `global_config.yml` if they are also defined there. 

</div>

<br>

<div id="div_id_RunThirdStage">

<hr>

### Running third stage cleaning in Matlab

If you already ran the first and second stage cleaning, simply run: 
```
fr_automated_cleaning(yearIn,'SITEID',7)
```
Note that the third stage is run with an argument of '7' (not '3'), and this stage is typically more computationally expensive than the first two stages.

Once you have set up all the relevant INI and YML configuration files, you can test all stages together using the following Matlab command:
```
fr_automated_cleaning(yearIn,'SITEID',[1 2 7])
```

</div>

<br>

<div id="div_id_FiltersThirdStage">

<hr>

### Third stage filters and variable names

The standalone flux variable names (i.e., FCH4, FC, H, LE) are copied directly from the second stage output, then wind sector and precipitation filters are applied to comply with eddy-covariance measurement theory, with no change to the variable name. For the variable names with suffixes following the flux variables, these suffixes represent different algorithms that we have applied sequentially, in the order that they appear (Table 5.5A). 

All these filters are set to be applied by default, but most of them can optionally be turned off by setting `Run: FALSE` in your third stage YML configuration file. As a reminder, algorithms that need parameter inputs have default values in the `global_config.yml` file which we as a group arrived at by doing sensitivity tests and reading the literature; however, these values can also be overwritten in your site-specific YML file if desired. 

*Table 5.5A. Third stage flux output variable definitions, descriptions, and site-specific options.*

| Suffix                         | Definition                             | Description   | Optional |
| ------------------------------ | -------------------------------------- | --------------- | --------- |
| No suffix                      | Standard cleaning                      | Applies wind direction and precipitation filtering to comply with eddy-covariance theory. | No. Runs by default. However, if you wish to, you can edit the wind sector and precipitation filter values, under `Standard_Cleaning/wakeFilter`, and `Standard_Cleaning/precipCutOff`. |
| _PI_SC                         | SC = Storage Correction                | Adds the storage term to the CO2 flux (NEE = FC + SC). | Yes. Set `Run: FALSE` if you do not want to add the storage term. | 
| _PI_SC_JSZ                     | Plus JSZ = z-score filter              | For outlier removal: uses a sliding window to calculate z-score, i.e., *(flux – mean)/(std. dev.)*, and removes data points with an absolute value greater than the threshold `z_thresh` set in `global_config.yml`. `window` size and `z_thresh` values can both be overwritten in your site-specific YML file if desired. | Yes. Set `Run: FALSE` if you do not want to removal outliers with this filter. |   
| _PI_SC_JSZ_MAD                 | Plus Median of Absolute Deviation (about the median) filter | For outlier removal: follows <a href="https://bg.copernicus.org/articles/3/571/2006/bg-3-571-2006.html" target="_blank" rel="noopener noreferrer">Papale et al. (2006)</a>.  | Yes. Set `Run: FALSE` if you do not want to removal outliers with this filter.  |
| _PI_SC_JSZ_MAD_RP              | Plus REddyProc applied (u-star filtering)  | CO2 flux partitioning and u-star filtering using <a href="https://bg.copernicus.org/articles/15/5015/2018/bg-15-5015-2018.html" target="_blank" rel="noopener noreferrer">REddyProc (Wutzler et al., 2018)</a>. Descriptions of suffixes applied to REddyProc output, e.g., `_uStar`, `U95`, `_orig`, and `_f`, can be found at <a href="https://www.bgc-jena.mpg.de/5624929/Output-Format" target="_blank" rel="noopener noreferrer">this link</a>.| Yes. Set `Run: FALSE` if you do not want to run flux partitioning and u-star filtering using REddyProc. |


</div>

<br>

<div id="div_id_RunAmerifluxStage">

<hr>

### Output to Ameriflux CSV file

Finally, once you have inspected your clean data and are happy with your INI files, you can output the data to a CSV file formatted for submission to Ameriflux. In case you do not want/need to rerun the cleaning (the third stage can be computationally expensive), simply run:
```
fr_automated_cleaning(yearIn,'SITEID',8)
```
Alternatively, to run all stages:
```
fr_automated_cleaning(yearIn,'SITEID',[1 2 7 8])
```

</div>

<br>

<div id="div_id_Tips">

<hr>

**TIPS**\
We recommend *not* editing the `global_config.yml` file directly as it is part of the `Biomet.net` library and therefore will create issues when you try to update the library (which you should be doing regularly). 

</div>