## 6. &nbsp; Data Visualization

<link rel="stylesheet" href="css/style.css">

Previously, we briefly mentioned some ways to visualize your data (section 4.2). This current section provides further details on visualizing data both using `Biomet.net` functions, and we also provide some standalone (non-pipeline) functions to help plot data from your database using Matlab, Python, and R. 

### Biomet.net functions

These are our recommended methods for viewing and analyzing your data, both during cleaning, and once you have real-time data flowing. 

#### Matlab:

There are several Matlab functions for *visualizing and analyzing data*:

* `plotApp`: a Matlab graphical user interface (GUI) which we recommend using during database set up and cleaning of your data (see section 6.1 for details).\
* `gui_Browse_Folder`: given a filepath, this function will open a new figure window and provide a dropdown containing all traces located at that filepath location. You can pick one or scroll through using the arrow buttons (see section 6.3).\
* `guiPlotTraces`: this is an older function with less utility than the `plotApp` GUI, but it still displays your data for quick viewing (see section 6.3).

#### RShiny:

There is also an R Shiny App which is useful for *viewing your flux data in real-time* (see section 6.2 for details). You can host this on an RShiny server to make your data publicly viewable.


### Standalone non-Biomet.net functions

Section 6.4 provides functions in Matlab, Python, and R, to help you load data for your general data analysis.


