## 8.1. &nbsp; Software: Current Recommended Versions

### Software Overview

* All three stages of data cleaning (plus conversion to Ameriflux output if needed) can be run from **Matlab**. Our `plotApp` for data visualization and analysis during data cleaning is run from Matlab too.

* Note that the third stage Matlab script invokes an **R**-script, which you will also need installed on your local computer. <!-- [link to R/RStudio installation instructions]. -->

* Additionally, our `R-Shiny` data visualization tool uses **R/R-Studio**, and we recommend this app for viewing your data in real-time.

* The scripts and tools that run the data cleaning are kept in a **Git** repository (called `Biomet.net`). These can be downloaded without having Git installed.<!-- [link to Clone_Biomet_Library.md]. -->

* Optionally, you can install Git and create your own **Github** account, in case you wish to contribute code to the Biomet.net library. <!-- [link to Install_Git_Create_Account_Optional.md]. --> 

* Some users may also need **Python** installed, for example, if you are processing high-frequency data. <!-- [link to Install_Python.md]. -->


### Recommended Software Versions:

Updated on: 5 November 2024 

| Software | Recommended version as of above date |
| -------- | ------------------- |
| Matlab   | **2024a** (at least 2023b)  |
| R        | v4.3.3              |
| RStudio  | 2024.09.0-375       |
| Python   | 3.9.6 for Mac       |
| Git      | Latest available <!-- (see link in 2_Install_Git_Create_Account_Optional.md) -->  |

Your computer/system administrators should be able to help you with all these installations if necessary. 


