## Data Cleaning Pipeline Documentation and Instructions

<!-- NOTE (Rosie, 13 June 2025): I spent a good amount of time trying to create custom figure numbering but it was not straightforward, so everything is manually numbered right now. Not ideal but may revisit. -->

Compiled by: Rosie Howard, 2024\
Edits and contributions: Zoran Nesic, Sara Knox, June Skeeter, Paul Moore, Karolina Bajda, and other EcoFlux Lab members and affiliates.

Revisions:\
- June 2025: Further detailed "full" documentation added, all moved to lab website.\
- March 2025: Full documentation added including pipeline features and further information to supplement the tutorial.\
- February 2025: "Recently Added Features" section 7.2 added. Full documentation still in progress.\
- October 2024: These are the "quick-start" instructions for new users of the data-cleaning pipeline. The full documentation will be made available at a later date.\

### Useful links 
- <a href="https://ecoflux-lab.github.io/PipelineDocumentation/7_2_Recently_Added_Features.html" target="_blank" rel="noopener noreferrer">Recently added pipeline features</a>
- Link to <a href="workshop/DataCleaningPipeline_Overview_Final_Web.zip">Overview of Data Cleaning Pipeline</a> slides presented during FLUXNET-CH4 V2.0 Workshop (on Day 1: Afternoon, and Day 2: Morning and Afternoon).
- Link to <a href="https://www.youtube.com/watch?v=wpeOC09LvS8&list=PLwwM5mY7NX4S62HBzrxXWvox_tWysd9un&ab_channel=EcoFluxLab" target="_blank" rel="noopener noreferrer">YouTube playlist of ALL presentations</a> from FLUXNET-CH4 V2.0 Workshop.

### Documentation outline

1. Motivation: The Importance of Flux Data Standardization and Reproducibility\
&emsp;1.1 &nbsp;Note on EddyPro Processing of High Frequency Data

2. Software Installation\
&emsp;2.1 &nbsp;Install Software: Git, and Create Github account (optional)\
&emsp;2.2 &nbsp;Download Biomet.net Library\
&emsp;2.3 &nbsp;Install Software: Matlab\
&emsp;2.4 &nbsp;Configure Matlab for Biomet.net\
&emsp;2.5 &nbsp;Install Software: R/RStudio\
&emsp;2.6 &nbsp;Install Software: Python (optional)

3. Data Cleaning Principles

<!-- 4. Set Up Project Directory Structure and Configure Matlab\ -->
4. Quick Start Tutorial - Recommended for First-Time Users\
&emsp;4.1 &nbsp;Quick Start Tutorial: Project Directory Structure and Matlab Configuration\
&emsp;4.2 &nbsp;Quick Start Tutorial: Create Database and Visualize\
&emsp;4.3 &nbsp;Quick Start Tutorial: Create First Stage INI File\
&emsp;4.4 &nbsp;Quick Start Tutorial: Create Second Stage INI File\
&emsp;4.5 &nbsp;Quick Start Tutorial: Third Stage and Ameriflux Output

5. Full Documentation: Features, Details, and Other Useful Information for Advanced Users\
&emsp;5.1 &nbsp;Full Documentation: Project Directory Structure and Matlab Configuration\
&emsp;5.2 &nbsp;Full Documentation: Create Database and Visualize\
&emsp;5.3 &nbsp;Full Documentation: First Stage INI Files\
&emsp;5.4 &nbsp;Full Documentation: Second Stage INI Files\
&emsp;5.5 &nbsp;Full Documentation: Third Stage and Ameriflux Output

6. Data Visualization\
&emsp;6.1 &nbsp;Matlab plotApp\
&emsp;6.2 &nbsp;R-Shiny App\
&emsp;6.3 &nbsp;Other Biomet Plotting Tools

7. Troubleshooting and FAQ\
&emsp;7.1 &nbsp;Recommended Software Versions\
&emsp;7.2 &nbsp;Recently Added Features


<!-- old section numbering -->
<!-- &emsp;4.1 &nbsp;Quick Start: Directory Structure and Matlab Configuration\
&emsp;4.2 &nbsp;Full Documentation: Set Up Project Directory Structure\
&emsp;4.3 &nbsp;Full Documentation: Configure Matlab for Data Structure -->

<!-- 5. Create Database from Raw Data and Visualize Contents\ -->

<!-- 5. Quick Start: Create Database\ -->
<!-- &emsp;5.1 &nbsp;Quick Start: Create Database and Visualize -->
<!-- &emsp;5.2 &nbsp;Full Documentation: Create Database -->

<!-- 6. Create Your Own INI Files for Data Cleaning\ -->

<!-- 6. Quick Start Tutorial: Create INI and Other Configuration Files for Data Cleaning\
&emsp;6.1 &nbsp;Quick Start: First Stage INI File\
&emsp;6.2 &nbsp;Quick Start: Second Stage INI File\
&emsp;6.3 &nbsp;Quick Start: Third Stage and Ameriflux Output -->

<!-- 7. Full Documentation: INI and Configuration Files - Details and Features\
&emsp;7.1 &nbsp;Full Documentation: First Stage INI file, Global Variables, Include Files, and Tags\
&emsp;7.2 &nbsp;Full Documentation: Second Stage INI\
&emsp;7.3 &nbsp;Full Documentation: Third Stage and Ameriflux Output -->
<!-- 
8. Data Visualization\
&emsp;8.1 &nbsp;Matlab plotApp\
&emsp;8.2 &nbsp;R-Shiny App

9. Troubleshooting and FAQ\
&emsp;9.1 &nbsp;Recommended Software Versions\
&emsp;9.2 &nbsp;Recommended Software Versions -->
