project:
  type: website
  output-dir: docs

website:
  title: "UBC Micromet"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Documentation.qmd
        text: Documentation
      - href: FieldWorkProcedures.qmd
        text: Field Work
    right:
      - icon: github
        href: https://github.com/ubc-micromet
        aria-label: Quarto GitHub
  sidebar:
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: about.qmd
          text: About
        - href: Publications.qmd
          text: Publications
    - id: docs
      title: "Documentation"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - Documentation.qmd
        - href: LabInfo.qmd
          text: Information for Current Lab Members
        - href: UsingGit.qmd
          text: Using Git
        - href: DatabaseWorkflows.qmd
          text: Database
    - id: field-work
      title: "Field Work"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - FieldWorkProcedures.qmd
        - href: Calibration.qmd
          text: Calibration
        - href: Cleaning.qmd
          text: Cleaning
        # - href: Checklists_and_logs/Checklists.qmd
        #   text: Checklists
  # page-footer:
  #   right:
  #     - icon: github
  #       href: https://github.com/ubc-micromet
  #       aria-label: Quarto GitHub
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



