project:
  type: website
  output-dir: docs

website:
  title: "EcoFlux Lab"
  navbar:
    background: light
    logo: /images/lab_logo/No_text_smaller.png
    left:
      - href: index.qmd
        text: Home
      - href: Documentation/index.qmd
        text: Documentation
      # - href: FieldWorkProcedures.qmd
      #   text: Site Monitoring & Field Work
      - href: Data.qmd
        text: Field Sites & Data
      - href: OutreachNews.qmd
        text: Outreach and News
      - href: PipelineDocumentation/PipelineDocumentation.qmd
        text: Pipeline Documentation
    right:
      - icon: github
        href: https://github.com/ecoflux-lab
        aria-label: Quarto GitHub
  
  sidebar:
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: Research.qmd
          text: Research
        - href: People.qmd
          text: People
        - href: Publications.qmd
          text: Publications
        - href: Join.qmd
          text: Join the lab
        - href: Meetings.qmd
          text: Lab Meetings
        - href: acknowledgement.qmd
          text: Territorial and Cultural Acknowledgement
    
    - id: documentation
      title: "Documentation"
      style: "floating"
      collapse: true
      align: left
      contents:
        - href: Documentation/index.qmd
          text: Overview
        - href: Documentation/DataWorkflows.qmd
          text: Data pipeline
        - href: Documentation/LabInfo.qmd
          text: Information for Current Lab Members
        - href: Documentation/UsingGit.qmd
          text: Using Git
        - href: Documentation/ReproducibleDataFlow.qmd
          text: Tips for Reproducible Data Flow
        - href: Documentation/Fieldwork/index.qmd
          text: Fieldwork maintenance and procedures  # No href here, just text
          contents:
            - href: Documentation/Fieldwork/DailyMonitoring.qmd
              text: Daily site monitoring
            - href: Documentation/Fieldwork/Calibration.qmd
              text: Calibration procedures
            - href: Documentation/Fieldwork/Cleaning.qmd
              text: Cleaning procedures
            - href: Documentation/Fieldwork/DataEntry.qmd
              text: Data entry
            - href: Documentation/Fieldwork/FieldworkProcedures.qmd
              text: Fieldwork Protocol & Procedures              
  
    - id: pipelinedocumentation
      title: "Pipeline Documentation"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: PipelineDocumentation/PipelineDocumentation.qmd
          text: Pipeline Documentation
        - href: PipelineDocumentation/1_Motivation.qmd 
          text: "1. Motivation: The Importance of Flux Data Standardization and Reproducibility"
          contents:
            - href: PipelineDocumentation/1_0_Note_High_Freq_Data_Processing.qmd
              text: "1.0 &nbsp; Note: High Frequency Data Processing"
        - href: PipelineDocumentation/2_SoftwareInstallation.qmd
          text: "2. Software Installation"
          contents:
            - href: PipelineDocumentation/2_1_Install_Git_Optional.qmd
              text: "2.1 &nbsp; Install Software: Git (optional)"
            - href: PipelineDocumentation/2_2_Clone_Biomet_Library.qmd
              text: "2.2 &nbsp; Clone Biomet Library"
            - href: PipelineDocumentation/2_3_Install_Matlab.qmd
              text: "2.3 &nbsp; Install Software: Matlab"
            - href: PipelineDocumentation/2_4_Configure_Matlab_For_Biomet.qmd
              text: "2.4 &nbsp; Configure Matlab for Biomet"
            - href: PipelineDocumentation/2_5_Install_R_Studio.qmd
              text: "2.5 &nbsp; Install Software: R/RStudio"
            - href: PipelineDocumentation/2_6_Install_Python_Optional.qmd
              text: "2.6 &nbsp; Install Software: Python (optional)"
        - href: PipelineDocumentation/3_Data_Cleaning_Principles.qmd
          text: "3. Data Cleaning Principles"
        - href: PipelineDocumentation/4_Quick_Start_Set_Up_Structure_Config.qmd
          text: "4. Quick Start: Project Directory Structure"
        - href: PipelineDocumentation/5_Quick_Start_Create_Database.qmd
          text: "5. Quick Start: Create Database"
          contents:
            - href: PipelineDocumentation/5_1_Quick_Start_Create_Database.qmd
              text: "5.1 &nbsp; Quick Start: Create Database and Visualize"
        - href: PipelineDocumentation/6_Quick_Start_Create_INI_Files.qmd
          text: "6. Quick Start: Create INI Files for Data Cleaning"
          contents:
            - href: PipelineDocumentation/6_1_Quick_Start_Create_First_Stage_INI.qmd
              text: "6.1 &nbsp; Quick Start: First Stage INI File"
            - href: PipelineDocumentation/6_2_Quick_Start_Create_Second_Stage_INI.qmd
              text: "6.2 &nbsp; Quick Start: Second Stage INI File"
            - href: PipelineDocumentation/6_3_Quick_Start_Third_Stage_Ameriflux.qmd
              text: "6.3 &nbsp; Quick Start: Third Stage and Ameriflux Output"
        - href: PipelineDocumentation/7_Data_Visualization.qmd
          text: "7. Data Visualization"
        - href: PipelineDocumentation/8_Troubleshooting_FAQ.qmd
          text: "8. Troubleshooting and FAQ"
          contents:
            - href: PipelineDocumentation/8_0_Recommended_Software_Versions.qmd
              text: "8.0 &nbsp; Recommended Software Versions"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

