project:
  type: website
  output-dir: docs

website:
  title: "EcoFlux Lab"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: Documentation/index.qmd
        text: Documentation
      # - href: FieldWorkProcedures.qmd
      #   text: Site Monitoring & Field Work
      - href: Data.qmd
        text: Field Sites & Data
      - href: OutreachNews.qmd
        text: Outreach and News
    right:
      - icon: github
        href: https://github.com/ecoflux-lab
        aria-label: Quarto GitHub
  sidebar:
    - id: home
      title: "Home"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - href: index.qmd
          text: Home
        - href: Research.qmd
          text: Research
        - href: People.qmd
          text: People
        - href: Publications.qmd
          text: Publications
        - href: Join.qmd
          text: Join the lab
        - href: Meetings.qmd
          text: Lab Meetings
        - href: acknowledgement.qmd
          text: Territorial and Cultural Acknowledgement
    - id: documentation
      title: "Documentation"
      style: "floating"
      collapse-level: 3
      align: left
      contents:
        - section: Documentation
          contents: Documentation
    #     - Documentation.qmd
    #     - href: DataWorkflows.qmd
    #       text: Data pipeline
    #     - href: LabInfo.qmd
    #       text: Information for Current Lab Members
    #     - href: UsingGit.qmd
    #       text: Using Git
    #     - href: ReproducibleDataFlow.qmd
    #       text: Tips for Reproducible Data Flow
    # - id: field-work
    #   title: "Site Monitoring & Field Work"
    #   style: "floating"
    #   collapse-level: 1
    #   align: left
    #   contents:
    #     - DailyMonitoring.qmd
    #     - FieldWorkProcedures.qmd
    #     - href: Calibration.qmd
    #       text: Calibration
    #     - href: Cleaning.qmd
    #       text: Cleaning
    #     - href: DataEntry.qmd
    #       text: Field Data Entry
        # - href: Checklists_and_logs/Checklists.qmd
        #   text: Checklists
  # page-footer:
  #   right:
  #     - icon: github
  #       href: https://github.com/ubc-micromet
  #       aria-label: Quarto GitHub
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


knitr:
  opts_chunk: 
    echo: false
    warning: false
    message: false

