---
title: "Publications"
format: 
  html:
    code-fold: true

bibliography: lab_publications_sorted.json
section-bibs-bibliography: lab_publications_sorted.json
section-bibs-level: 2 # May require edit to line 78 in _extensions/section-bibliographies.lua - have submitted issue
citeproc: False
csl: american-geophysical-union.csl

filters:
  - section-bibliographies
  - _extensions/bold-author.lua
  - _extensions/hide-me.lua
bold-auth-name:
  - family: Knox
    given: S. H.
  - family: Knox
    given: S.
  - family: Skeeter
    given: J.
  - family: Lee
    given: S.-C.
  - family: Nesic
    given: Z.
  - family: Ketler
    given: R.
  - family: Lu
    given: T.-Y.  
  - family: Russell
    given: S. J.
  - family: Russell
    given: S.
  - family: Katrina
    given: P.
  - family: Ng
    given: D.
  - family: Nyberg
    given: M.
  - family: Satriawan
    given: T.
  - family: Howard
    given: R.
  - family: Moore
    given: P.
  - family: Zhang
    given: H.
  - family: Li
    given: J.
---

<!-- To update the publication list, first export a zotero CSL JSON file and rename as lab_publications. Then run code 'sort_publication.R before running this script to generate file lab_publications_sorted.json -->

## Peer Reviewed Journal Articles

For the most up-to-date list, please visit my [Google Scholar page](https://scholar.google.com/citations?user=-yNUihgAAAAJ&hl=en)

::: hide-me

@http://zotero.org/users/16062011/items/JY2VC3VC 
@http://zotero.org/users/16062011/items/3BPUN9KS 
@http://zotero.org/users/16062011/items/Q5XQHTKF 
@http://zotero.org/users/16062011/items/VWPGVTX9 
@http://zotero.org/users/16062011/items/KF3FZHKR 
@http://zotero.org/users/16062011/items/NF9K25S8 
@http://zotero.org/users/16062011/items/PENASLKE 
@http://zotero.org/users/16062011/items/MZJAMZWT 
@http://zotero.org/users/16062011/items/HE5M5PXH 
@http://zotero.org/users/16062011/items/LETDFHRC 
@http://zotero.org/users/16062011/items/YAC2IAA7 
@http://zotero.org/users/16062011/items/GLD8F8CY 
@http://zotero.org/users/16062011/items/UVLAI497 
@http://zotero.org/users/16062011/items/SKFPZSXX 
@http://zotero.org/users/16062011/items/7YA7SH7T 
@http://zotero.org/users/16062011/items/F9TE4UMJ 
@http://zotero.org/users/16062011/items/6BJRVDEB 
@http://zotero.org/users/16062011/items/BU7N6R37 
@http://zotero.org/users/16062011/items/IDCMX85X 
@http://zotero.org/users/16062011/items/7SLFG6MH 
@http://zotero.org/users/16062011/items/AFYCKU2V 
@http://zotero.org/users/16062011/items/ZKNSTGZB 
@http://zotero.org/users/16062011/items/5SCBHQB6 
@http://zotero.org/users/16062011/items/VH9CD4VJ 
@http://zotero.org/users/16062011/items/Q46MCKJ9 
@http://zotero.org/users/16062011/items/FA354G5H 
@http://zotero.org/users/16062011/items/C8XW8SYE 
@http://zotero.org/users/16062011/items/H52D8RBS 
@http://zotero.org/users/16062011/items/VI9NLWH7 
@http://zotero.org/users/16062011/items/ABJF74LD 
@http://zotero.org/users/16062011/items/A2IBX8JX 
@http://zotero.org/users/16062011/items/J63JF23R 
@http://zotero.org/users/16062011/items/8GBBVPC2 
@http://zotero.org/users/16062011/items/L627JN4X 
@http://zotero.org/users/16062011/items/SSM82IV9 
@http://zotero.org/users/16062011/items/AEC37JT7 
@http://zotero.org/users/16062011/items/B9VQIP4X 
@http://zotero.org/users/16062011/items/LMHEZYYT 
@http://zotero.org/users/16062011/items/9L6JMHWQ 
@http://zotero.org/users/16062011/items/SG7Y5E7Q 
@http://zotero.org/users/16062011/items/LISCEGYQ 
@http://zotero.org/users/16062011/items/VBTH9UW6 
@http://zotero.org/users/16062011/items/49BLPKGE 
@http://zotero.org/users/16062011/items/WNTQDLMD 
@http://zotero.org/users/16062011/items/LF9362FN 
@http://zotero.org/users/16062011/items/LW3U4Y3N 
@http://zotero.org/users/16062011/items/9RXTSCBD 
@http://zotero.org/users/16062011/items/PEVMYWVQ 
@http://zotero.org/users/16062011/items/24JGQI7V 
@http://zotero.org/users/16062011/items/KH5T8V7X 
@http://zotero.org/users/16062011/items/MXN4GBPB 
@http://zotero.org/users/16062011/items/UN9TTLA3 
@http://zotero.org/users/16062011/items/LDXNX3GH 
@http://zotero.org/users/16062011/items/N577ZFH9 
@http://zotero.org/users/16062011/items/HP7SAGKH 
@http://zotero.org/users/16062011/items/L9QKA9Z3 
@http://zotero.org/users/16062011/items/SP2K5JZ6 
@http://zotero.org/users/16062011/items/ND77BDD8 
@http://zotero.org/users/16062011/items/TFJYWJZU 
@http://zotero.org/users/16062011/items/77YZQPYQ 
@http://zotero.org/users/16062011/items/ESXR5IG5 
@http://zotero.org/users/16062011/items/AJT74ZWC 
@http://zotero.org/users/16062011/items/QYW8KUM8 
@http://zotero.org/users/16062011/items/H4KFW5N7 
@http://zotero.org/users/16062011/items/L6VRK8R7 
@http://zotero.org/users/16062011/items/XEXBU69I 
@http://zotero.org/users/16062011/items/VEUNFEH8 
@http://zotero.org/users/16062011/items/43QN3NDK 
@http://zotero.org/users/16062011/items/TA4KGBKU 
@http://zotero.org/users/16062011/items/INNRTGQZ 
@http://zotero.org/users/16062011/items/SI7A5IXI 
@http://zotero.org/users/16062011/items/PV5GWCRH 

:::

## Theses

::: hide-me

@http://zotero.org/users/16062011/items/RBPNGKKK 
@http://zotero.org/users/16062011/items/CWYFA99M 
@http://zotero.org/users/16062011/items/DKYGTX2X 
@http://zotero.org/users/16062011/items/KXPVWMI3 
@http://zotero.org/users/16062011/items/H2EMF8XB 

:::

## Research Talks & Poster Presentations

<!--<p style="margin-bottom:0; margin-left: 60px; text-indent: -35px;"><b>Yang, X.</b>(2025, May). Decoding tidal wetland change and resilience for the sustainable coastal environment.</p> -->

<p style="margin-bottom:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2025, May). Monitoring Methane Dynamics Across Canadian Wetlands.<i> 2025 Canadian Geophysical Union (CGU) Annual Meeting,</i> Saskatoon, SK.</p> 

<p style="margin : 0; padding-top:0;margin-left: 60px; text-indent: -35px;"><b>Howard, R., Nesic, Z., Skeeter, J.,</b> Moore, P.,<b> Knox, S. H.,</b> Strack, M. (2025, May). Overview of Data Cleaning Pipeline for Standardizing Eddy-Covariance Data (Poster). <i>2025 CMOS-CGU Joint Congress,</i> Saskatoon, SK.</p> 

<p style="margin : 0; padding-top:0;margin-left: 60px; text-indent: -35px;"><b>Ahongshangbam, J.,</b> Badiou, P.,<b> Nesic, Z., Ng, D., Knox, S. H.</b> (2025, May). Spatio-temporal variability of CO2 and CH4 fluxes in wetlands across the Prairie Pothole Region, Canada (Poster). <i>2025 CMOS-CGU Joint Congress,</i> Saskatoon, SK.  </p> 

<p style="margin : 0; padding-top:0;margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2025, March). Ecosystem Responses to Global Climate Change. <i>FSCI 198,</i> McGill University, Montreal, QC. </p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Ahongshangbam, J.</b> (2025, March). Surface cooling potential of wetlands across the Prairie Pothole Region of Canada. <i>Ducks Unlimited Canada: Institute for Wetland and Waterfowl Research Roundup Webinar Series (online).</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2025, January). Integrating micrometeorological measurements, remote sensing, and modeling to better understand wetland processes, feedbacks, and climate benefits. <i>AOS Seminar Series, </i>McGill University, Montreal, QC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b> (2024, December). Improving wetland methane upscaling across site to global scales.<i> American Geophysical Union Fall Meeting,</i> Washington, DC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Li, F., Yuan, K., Zhu, Q., Chen, M., Hoyt, A., <b>Knox, S. H.,</b> McNicol, G., Riley, W. J., & Jackson, R. B. (2024, December). Global CH₄ emissions from small wetlands during 2002–2022. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Cosio, E., Salinas, N., Stern, R., Tito, R., Ramos-Chang, E., Becker, R., Bereswill, S.,<b> Knox, S. H., </b> Jackson, R. B., Trachte, K., Negron Juarez, R. I., Cruz, R., Thomas, C. K., Nina-Quispe, A., Urquiza-Muñoz, J. D., Jan, S., Kirsten, T., Hoyt, A., Fuentes, J. D., & Bendix, J. (2024, December). AndesFlux: Measuring ecohydrological responses of forests to climate change along an environmental gradient to bridge observational gaps in the western Amazon. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Stern, R., Cosio, E., Cruz, R., Ramos-Chang, E., Hoyt, A., Jackson, R. B., Salinas, N., Thomas, C. K., <b>Knox, S. H.,</b> Li, F., & Negron Juarez, R. (2024, December). Carbon budget considering emission and sink patterns of both CO₂ and CH₄ in Southwestern Amazonia (Poster). <i>American Geophysical Union Fall Meeting, </i>San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Haber, L., Bohrer, G., <b>Knox, S. H., </b>Neubauer, S. C., <b>Poppe, K., </b>Priddy, M., <b>Russell, S.,</b> Weil, M., & Gough, C. M. (2024, December). Sink or source?: The carbon dynamics of a restored tidal freshwater wetland in Virginia. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Hoyt, A., Stern, R., <b>Knox, S. H.,</b> Bonal, D., Cosio, E., Martins Custodio, L. L., Deshmukh, C. S., Forsberg, B., Gondwe, M., Lamb, J., Nardi, N., Nurholis, N., Riley, W. J., Salinas, N., Susanto, A. P., Yusnia, K., Jackson, R. B., Li, F., Boeckx, P. M., Brechet, L. M., Cruz, R., Delwiche, K. B., Fleischmann, A. S., Gallego-Sala, A. V., Helfter, C., McNicol, G., Norpon Juarez, R., Ramos-Chang, E., Regina Roberti, D., dos Santos, D., Thomas, C. K., & Zhu, Q. (2024, December). Methane fluxes from natural ecosystems: A pantropical network (Poster). <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Li, M., Jackson, R. B., Li, F., Delwiche, K., & <b>Knox, S. H. </b> (2024, December). Divergent responses of environmental driver importance on wetland CH₄ and net CO₂ fluxes under hot extremes. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2024, November). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands. <i>CEEB Seminar Series,</i> McGill University, Montreal, QC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Howard, R., Nesic, Z.,  Knox, S. H.,</b> Moore, P., <b>Skeeter, J.</b> (2024, October). Overview of Data Cleaning Pipeline: Overview of Theory and Instructions. <i>FLUXNET-CH4 V2.0 Data Processing Workshop,</i> Berkeley, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Poppe, K. P., Knox, S. H., Russell, S.,</b>  Oikawa, P., Matsumura, M., Gough, C., Haber, L., Shafer, K., Dhakal, S., Vargas, R., Windham-Myers, L., & Stuart-Haentjens, E. (2024, September). Exploring the impact of tidal flooding on methane fluxes across a North American network of tidal marshes (Poster). <i>AmeriFlux Annual Meeting,</i> Berkeley, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2024, September). Improving understanding of the global carbon cycle by combining observations, machine learning and process-based models. <i>Trottier Space Institute Symposium,</i> McGill University, Montreal, QC.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Ahongshangbam, J.,</b> Badiou, P., Scott, T., <b>Ng, D., Nesic, Z.,</b> Glenn, A., & <b>Knox, S. H. </b>(2024, May). Surface cooling potential of wetlands across the Prairie Pothole Region of Canada. <i>CGU 2024, </i>Ottawa, ON.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Lu, T.-Y., Russell, S., & Knox, S. H. </b>(2024, April). Controls on interannual variability of carbon dioxide (CO₂) in a coastal wetland ecosystem: Insights from two-year measurements in a temperate salt marsh (Poster).<i> EGU General Assembly 2024, </i>Vienna, Austria. [https://doi.org/10.5194/egusphere-egu24-14700](https://doi.org/10.5194/egusphere-egu24-14700) </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2024, March). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands. <i>EPS Seminar Series,</i> McGill University, Montreal, QC.  </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2024, February). Wetlands & climate change. <i>Soup and Science Lecture Series,</i> McGill University, Montreal, QC.  </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H., </b>Badiou, P.,<b> Lee, S. C., Ng, D., </b>Bogard, M., & <b> Nesic, Z.</b> (2023, December). The importance of salinity in regulating greenhouse gas fluxes in wetlands of the Prairie Pothole Region. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Zhang, Z., Bansal, S., Chang, K.-Y., et al. (2023, December). Characterizing performance of freshwater wetland methane models across time scales at FLUXNET-CH₄ sites using wavelet analyses. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Oikawa, P. Y., Silberman, J., Matsumura, M., et al. (2023, December). Constraining CO₂ and CH₄ fluxes from diverse tidal wetlands: Measurements and modeling across a network of eddy covariance sites in North America and Canada. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. Abstract available at: [https://ui.adsabs.harvard.edu/abs/2023AGUFM.B53B..06O/abstract](https://ui.adsabs.harvard.edu/abs/2023AGUFM.B53B..06O/abstract). </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Fluet-Chouinard, E., et al. (2023, December). Detection of vegetated and forested wetlands and their inundation status with multi-temporal PALSAR and Landsat across conterminous United States. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Bogard, M. J., et al. (2023, December). Salinity causes widespread restriction of methane emissions from small inland waters. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Oikawa, P., Stuart-Haëntjens, E., Matsumura, M., Silberman, J., Gough, C., Haber, L., Tenda, S., Schäfer, K., Dhakal, S., <b>Knox, S. H., Poppe, K., Russell, S.,</b> Vargas, R., Hill, A., & Windham-Myers, L. (2023, December). Constraining CO₂ and CH₄ fluxes from diverse tidal wetlands: Measurements and modeling across a network of eddy covariance sites in North America and Canada. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Harber, L., Windham-Myers, L., <b>Knox, S. H., Russell, S.,</b> Gough, C., Stapel, A., Stuart-Haëntjens, E., & <b>Poppe, K.</b> (2023, December). Fluxes in the Tidal Fresh: Assessing hourly to annual drivers of coupled CH₄ and CO₂ fluxes in a tidal freshwater wetland. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Skeeter, J.</b> (2023, December). Tools and guidance for applying neural networks to eddy covariance data. <i>American Geophysical Union Fall Meeting,</i> San Francisco, CA. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2023, November). Network science: unlocking novel insights on regional and global methane cycling (virtual presentation). <i>Tipping Discussion Series Event on Methane.</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Harber, L., Windham-Myers, L., <b>Knox, S. H., Russell, S.,</b> Gough, C., Stapel, A., Stuart-Haëntjens, E., & <b>Poppe, K.</b> (2023, October). Fluxes in the Tidal Fresh: Assessing hourly to annual drivers of coupled CH₄ and CO₂ fluxes in a tidal freshwater wetland. <i>AmeriFlux Annual Meeting,</i> Gardner, MA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Silberman, J., Matsumura, M., Shahan, J., Stuart-Haëntjens, E., Bergamaschi, B., Nakatsuka, K., Windham-Myers, L., Sturtevant, C., <b>Knox, S. H.,</b> Labedens Mur, S., & Oikawa, P. (2023, October). A comparative analysis of atmospheric carbon and lateral DIC fluxes in tidal marshes with differing environmental conditions and management practices.<i> AmeriFlux Annual Meeting,</i> Gardner, MA, United States.  </p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Ng, D., </b>Rey-Sanchez, C., Black, A. T., Badiou, P., & <b>Knox, S. H.</b> (2023, October). Characterization and prediction of methane spatial heterogeneity within and beyond a flux tower footprint (Poster). <i>AmeriFlux Annual Meeting,</i> Gardner, MA, United States.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;">Oikawa, P., Stuart-Haëntjens, E., Matsumura, M., Silberman, J., Gough, C., Haber, L., Tenda, S., Schäfer, K., Dhakal, S., <b>Knox, S. H., Poppe, K., Russell, S., </b>Vargas, R., Hill, A., & Windham-Myers, L. (2023, October). Constraining CO₂ and CH₄ fluxes from diverse tidal wetlands: Measurements and modeling across a network of eddy covariance sites in North America and Canada. <i>AmeriFlux Annual Meeting,</i> Gardner, MA, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2023, October). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands. <i>UQAM Ecology, Evolution, Behaviour and Ecotoxicology Seminar,</i> Montreal, QC.  </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2023, September). FLUXNET-CH₄: improving understanding of wetland methane fluxes from site to global scales. <i>Observation Infrastructure for Natural Methane Emissions,</i> Yale Center for Natural Carbon Capture, New Haven, CT, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2023, June). FLUXNET-CH₄: a global eddy covariance CH₄ database to answer regional and global questions related to CH₄ cycling. <i>Canadian Society for Chemistry,</i> Vancouver, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Poppe, K., Knox, S. H., Lu, T.-Y., Russell, S., Nesic, Z., & Lee, S. C.</b> (2023, June). Measuring ecosystem-scale greenhouse gas fluxes in tidal marshes in British Columbia. <i>Coastal Zone Canada Conference,</i> Victoria, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Skeeter, J., & Knox, S. H. </b>(2023, May). A framework for applying neural networks to eddy covariance data. <i>Canadian Geophysical Union Annual Meeting,</i> Banff, AB.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Skeeter, J., & Knox, S. H. </b>(2023, April). Ongoing and proposed research in the Burns Bog Ecological Conservancy Area. <i>CLASSIC Workshop,</i> Victoria, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b> Knox, S. H., & Skeeter, J.</b> (2023, March). UBC Micrometeorology Lab Studies Review. <i>Burns Bog Ecological Conservancy Area Scientific Advisory Panel Meeting,</i> Burnaby, BC.</p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2023, March). FLUXNET-CH₄: a global eddy covariance CH₄ database to answer regional and global questions related to CH₄ cycling (virtual presentation).<i> Artificial Intelligence for the Methane Cycle (AI4CH₄),</i> US Department of Energy Workshop Series. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2023, March). Greenhouse gas flux research at Burns Bog. <i>Burns Bog Ecological Conservancy Area Scientific Advisory Panel Meeting,</i> Burnaby, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2022, December). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands. <i>American Geophysical Union Fall Meeting,</i> Chicago, IL, United States. </p>  

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Lu, T.-Y., Russell, S. J., Skeeter, J., Lee, S., </b>Oikawa, P., & <b>Knox, S. H.</b> (2022, December). Investigating environmental controls on carbon exchange and predicting gaseous carbon fluxes at a salt marsh in British Columbia (Poster). <i>American Geophysical Union Fall Meeting,</i> Chicago, IL, United States. </p>  

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Ng, D., & Knox, S. H. </b>(2022, December). Characterizing within-footprint spatial heterogeneity of CH₄ emissions in freshwater wetlands through remote sensing and footprint-weighted flux maps.<i> American Geophysical Union Fall Meeting,</i> Chicago, IL, United States. </p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2022, November). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands.<i> IRES Seminar Series, </i>University of British Columbia, Vancouver, BC. </p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H., Ng, D., Lee, S.-C., Nesic, Z.,</b> & Badiou, P. (2022, September). Quantifying carbon and greenhouse gas fluxes in wetlands in the Prairie Pothole Region, Canada (Poster). <i>2022 AmeriFlux Annual Meeting,</i> Pellston, MI, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2022, September). Coastal wetland conservation: Nature-based climate solution (virtual presentation). <i>Rotary Club of Steveston. </i></p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Satriawan, T., Nyberg, M., Lee, S. C., Nesic, Z.,</b>Black, T. A., Johnson, M., <b> Knox, S. H.</b> (2022, September).Interannual Variability of Carbon Dioxide (CO2) and Methane (CH4) Fluxes in a Rewetted Temperate Bog over a 5-Year Period (virtual presentation).&nbsp;<i>2022 AmeriFlux Annual Meeting.</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Satriawan, T., Nyberg, M., Lee, S. C., Nesic, Z.,</b>Black, T. A., Johnson, M., <b> Knox, S. H.</b> (2022, June). Interannual Variability of Carbon Dioxide (CO2) and Methane (CH4) Fluxes in a Rewetted Temperate Bog over a 5-Year Period (Poster).<i> AsiaFlux Conference 2022, </i> Kuching, Malaysia. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2022, May). Measuring the breathing of the biosphere from site to global scales. <i>Weather Forecast Research Team Seminar Series, </i>University of British Columbia, Vancouver, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2022, April). Wetlands in a changing world: processes, feedbacks and the climate benefits of wetlands (virtual presentation). <i>Department of Earth and Environmental Sciences Seminar Series,</i> University of Illinois at Chicago. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Satriawan, T., Nyberg, M., Lee, S. C., Nesic, Z.,</b>Black, T. A., Johnson, M., <b> Knox, S. H.</b> (2021, December). Interannual Variability of CO2 and CH4 Fluxes in a Temperate Bog over a 5-Year Period (virtual poster).<i> American Geophysical Union Fall Meeting.</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2021, December). FLUXNET-CH₄ – a global database of eddy covariance methane flux measurements (virtual presentation). <i>AsiaFlux Conference 2021.</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2021, April). Biosphere-atmosphere interactions in a changing world (virtual presentation). <i>Rouse Climate Lecture,</i> McMaster University. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2021, March). Measuring ecosystem-scale greenhouse gas fluxes in tidal marshes in British Columbia (virtual presentation). <i>Pacific Northwest Blue Carbon Working Group Workshop. </i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Russell, S., Knox, S. H.,</b> Windham-Myers, L., & Bergamaschi, S. (2020, December). Increased salinity decreases annual gross primary productivity of a brackish wetland (Virtual Poster).<i> American Geophysical Union Fall Meeting. </i></p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Nyberg, M., Knox, S. H.,</b> Black, T., Johnson, M., <b>Ketler, R., & Nesic, Z. </b>(2020, December). Impacts of restoration and climate variability on peatland greenhouse gas fluxes (Virtual Poster).<i> American Geophysical Union Fall Meeting.</i> </p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Satriawan, T., Nyberg, M., Lee, S. C., Nesic, Z.,</b>Black, T. A., Johnson, M., <b> Knox, S. H.</b> (2020, December). Interannual Variability of CO2 and CH4 Fluxes in a Temperate Bog over a 5-Year Period (Virtual Poster). <i>American Geophysical Union Fall Meeting.</i> </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2020, August). FLUXNET-CH₄ synthesis activity (virtual meeting). <i>Ecological Society of America Annual Meeting. </i></p> 

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b> (2019, December). Wetland FLUXNET synthesis for CH₄: understanding CH₄ fluxes at daily to interannual timescales.<i> American Geophysical Union Fall Meeting,</i> Washington, DC, United States. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b>(2019, July). Biosphere-atmosphere interactions in a changing world. <i>Atmospheric Science Seminar,</i> University of British Columbia, Vancouver, BC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H. </b> (2019, May). Wetlands in a changing world: processes, feedbacks & the climate benefits of wetlands. <i>20th Annual Mer Bleue Peatland Science Workshop,</i> McGill University, Montreal, QC. </p>

<p style="margin : 0; padding-top:0; margin-left: 60px; text-indent: -35px;"><b>Knox, S. H.</b> (2019, January). Blue Carbon Research: From California to British Columbia. <i>Blue Carbon Workshop, </i> West Coast Environmental Law, Surrey, BC. </p>


